In [5]:
import pandas as pd

df = pd.read_csv('./data/405957090_5천만건(hum,voc포함).csv')
df['updated'] = pd.to_datetime(df['updated'])

In [9]:
baby = df[df['device_id']==2273]
baby['updated'].dt.date.unique()

array([datetime.date(2023, 9, 19), datetime.date(2023, 9, 17),
       datetime.date(2023, 9, 16), datetime.date(2023, 9, 5),
       datetime.date(2023, 8, 9), datetime.date(2023, 8, 8),
       datetime.date(2023, 8, 7), datetime.date(2023, 7, 16),
       datetime.date(2023, 7, 15), datetime.date(2023, 7, 14),
       datetime.date(2023, 7, 13), datetime.date(2023, 6, 24),
       datetime.date(2023, 5, 14)], dtype=object)

In [10]:
import datetime

oneday_baby = baby[baby['updated'].dt.date == datetime.date(2023, 9, 16)]
oneday_baby

,_id,device_id,days,sex,temperature,humidity,voc,updated
12449006,393488134,2273,869,0,3023,4923,30329,2023-09-16 23:59:59
12449008,393488132,2273,869,0,3023,4922,30360,2023-09-16 23:59:58
12449009,393488131,2273,869,0,3023,4921,30311,2023-09-16 23:59:57
12449010,393488130,2273,869,0,3023,4921,30339,2023-09-16 23:59:56
12449011,393488129,2273,869,0,3023,4922,30332,2023-09-16 23:59:55
...,...,...,...,...,...,...,...,...
12768063,393169077,2273,868,0,-1,-1,-1,2023-09-16 01:42:08
12768064,393169076,2273,868,0,-1,-1,-1,2023-09-16 01:42:07
12768065,393169075,2273,868,0,-1,-1,-1,2023-09-16 01:42:06
12768066,393169074,2273,868,0,-1,-1,-1,2023-09-16 01:42:05
12768067,393169073,2273,868,0,-1,-1,-1,2023-09-16 01:42:04

In [ ]:
pd.date_range

In [ ]:
import koreanize_matplotlib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates


device_num = 2273

# 날짜 범위 설정 (2023-05-08 ~ 2023-11-13)
dates = pd.date_range(start=oneday_baby[oneday_baby["device_id"]==device_num].index.astype(str).str[:16].unique()[0],
                      end=oneday_baby[oneday_baby["device_id"]==device_num].index.astype(str).str[:16].unique()[-1])

for i in range(0, 24):
    # 해당 시간의 데이터만 선택
    onetime_baby = oneday_baby[oneday_baby['updated'].dt.hour == i]

    # 데이터를 시각화
    fig, ax1 = plt.subplots(figsize=(15, 8))

    # 첫 번째 축
    ax1.plot(onetime_baby.index, onetime_baby['temperature'], label='Temperature', color='tab:red')
    ax1.set_xlabel('Time')
    ax1.set_ylabel('Temperature', color='tab:red')
    ax1.xaxis.set_major_locator(mdates.HourLocator(interval=1))  # 1시간 간격으로 주요 눈금 설정
    ax1.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
    ax1.set_xlim([onetime_baby.index[0], onetime_baby.index[-1]])  # 데이터에 따른 xlim 설정
    ax1.tick_params(axis='y', labelcolor='tab:red')

    # 두 번째 축
    ax2 = ax1.twinx()
    ax2.plot(onetime_baby.index, onetime_baby['voc'], label='VOC', color='tab:blue')
    ax2.set_ylabel('VOC', color='tab:blue')
    ax2.tick_params(axis='y', labelcolor='tab:blue')

    # 세 번째 축
    ax3 = ax1.twinx()
    ax3.plot(onetime_baby.index, onetime_baby['humidity'], label='Humidity', color='tab:green')
    ax3.set_ylabel('Humidity', color='tab:green')
    ax3.tick_params(axis='y', labelcolor='tab:green')

    # 그래프의 제목과 범례 설정
    plt.title(f'Temperature, VOC, and Humidity on {onetime_baby.index[0].date()} at {i}:00')
    fig.tight_layout()

    # 그리드를 표시
    ax1.grid(True)

    # 범례 표시
    ax1.legend(loc='upper left')
    ax2.legend(loc='upper right')

    # 그래프를 출력
    plt.show()